#!/usr/bin/env bash
set -Eeuo pipefail

BASE_URL="https://raw.githubusercontent.com/Terranom674/Gitea-Connector/main/install"

echo
echo "============================================================"
echo " Gitea MCP - Proxmox Installer"
echo "============================================================"
echo "Sprache wählen / Choose language:"
echo "  1) Deutsch"
echo "  2) English"
printf 'Auswahl / Selection [1]: '
read -r LANGUAGE
LANGUAGE="${LANGUAGE:-1}"

case "$LANGUAGE" in
  1|de|DE|Deutsch|deutsch)
    SCRIPT="proxmox-de-v2.sh"
    echo
    echo "============================================================"
    echo " Vorbereitung"
    echo "============================================================"
    echo "Für die vollständige Installation benötigst du später:"
    echo
    echo "1. Gitea-Basis-URL"
    echo "2. Gitea-Zugriffstoken"
    echo "3. OpenAI Secure MCP Tunnel-ID"
    echo "4. OpenAI Tunnel Runtime API-Key"
    echo
    echo "WICHTIG - OpenAI-Tunnel vorher vorbereiten:"
    echo
    echo "1. Falls noch nicht vorhanden, einen OpenAI-Platform-Account"
    echo "   erstellen bzw. dich auf der OpenAI Platform anmelden."
    echo "2. In der OpenAI Platform die Seite 'Tunnels' öffnen."
    echo "3. Dort über 'Create tunnel' einen neuen Tunnel erstellen."
    echo "4. Die danach angezeigte Tunnel-ID (tunnel_...) kopieren."
    echo "5. Einen passenden Tunnel Runtime API-Key erstellen."
    echo "6. Tunnel-ID und Runtime API-Key bereithalten."
    echo
    echo "Tunnel-ID und Runtime API-Key werden NICHT vom Installer erzeugt."
    echo "Ohne diese beiden Werte kann Abschnitt 4 nicht abgeschlossen werden."
    echo
    echo "Ausführliche Vorbereitung: README.md / Installationshandbuch"
    echo
    ;;
  2|en|EN|English|english)
    SCRIPT="proxmox-en-v2.sh"
    echo
    echo "============================================================"
    echo " Preparation"
    echo "============================================================"
    echo "For the complete installation you will need:"
    echo
    echo "1. Gitea base URL"
    echo "2. Gitea access token"
    echo "3. OpenAI Secure MCP Tunnel ID"
    echo "4. OpenAI Tunnel Runtime API key"
    echo
    echo "IMPORTANT - prepare the OpenAI tunnel first:"
    echo
    echo "1. If you do not already have one, create an OpenAI Platform"
    echo "   account or sign in to the OpenAI Platform."
    echo "2. Open the 'Tunnels' page in the OpenAI Platform."
    echo "3. Select 'Create tunnel' and create a new tunnel."
    echo "4. Copy the tunnel ID (tunnel_...) shown afterwards."
    echo "5. Create a suitable tunnel runtime API key."
    echo "6. Keep the tunnel ID and runtime API key ready."
    echo
    echo "The tunnel ID and runtime API key are NOT generated by this installer."
    echo "Without both values, section 4 cannot be completed."
    echo
    echo "Detailed preparation: README.md / installation guide"
    echo
    ;;
  *)
    echo "Ungültige Auswahl / Invalid selection." >&2
    exit 1
    ;;
esac

exec bash <(curl -fsSL "$BASE_URL/$SCRIPT")