#!/usr/bin/env bash
set -Eeuo pipefail

# Frische Debian-LXC-Templates enthalten nicht immer en_US.UTF-8.
# C.UTF-8 ist auf Debian vorhanden und vermeidet Locale-Warnungen bei apt/Docker.
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
unset LANGUAGE

BASE_URL="https://raw.githubusercontent.com/Terranom674/Gitea-Connector/main/install"

echo
echo "============================================================"
echo " Gitea MCP - Proxmox Installer"
echo "============================================================"
echo "Sprache wählen / Choose language:"
echo "  1) Deutsch"
echo "  2) English"
printf 'Auswahl / Selection [1]: '
read -r LANGUAGE
LANGUAGE="${LANGUAGE:-1}"

case "$LANGUAGE" in
  1|de|DE|Deutsch|deutsch)
    SCRIPT="proxmox-de-v2.sh"
    LANG_MODE="de"
    echo
    echo "============================================================"
    echo " Vorbereitung"
    echo "============================================================"
    echo "Für die vollständige Installation benötigst du später:"
    echo
    echo "1. Gitea-Basis-URL"
    echo "2. Gitea-Zugriffstoken"
    echo "3. OpenAI Secure MCP Tunnel-ID"
    echo "4. OpenAI Tunnel Runtime API-Key"
    echo
    echo "WICHTIG - OpenAI-Tunnel vorher vorbereiten:"
    echo
    echo "1. Falls noch nicht vorhanden, einen OpenAI-Platform-Account"
    echo "   erstellen bzw. dich auf der OpenAI Platform anmelden."
    echo "2. In der OpenAI Platform die Seite 'Tunnels' öffnen."
    echo "3. Dort über 'Create tunnel' einen neuen Tunnel erstellen."
    echo "4. Die danach angezeigte Tunnel-ID (tunnel_...) kopieren."
    echo "5. Unter API Keys einen neuen Secret Key erstellen:"
    echo "   Owned by: You, Permissions: Restricted, nur Tunnels: All selected."
    echo "6. Tunnel-ID und Runtime API-Key bereithalten."
    echo
    echo "Tunnel-ID und Runtime API-Key werden NICHT vom Installer erzeugt."
    echo "Ohne diese beiden Werte kann Abschnitt 4 nicht abgeschlossen werden."
    echo
    echo "Ausführliche Vorbereitung: README.md / Installationshandbuch"
    echo
    ;;
  2|en|EN|English|english)
    SCRIPT="proxmox-en-v2.sh"
    LANG_MODE="en"
    echo
    echo "============================================================"
    echo " Preparation"
    echo "============================================================"
    echo "For the complete installation you will need:"
    echo
    echo "1. Gitea base URL"
    echo "2. Gitea access token"
    echo "3. OpenAI Secure MCP Tunnel ID"
    echo "4. OpenAI Tunnel Runtime API key"
    echo
    echo "IMPORTANT - prepare the OpenAI tunnel first:"
    echo
    echo "1. If you do not already have one, create an OpenAI Platform"
    echo "   account or sign in to the OpenAI Platform."
    echo "2. Open the 'Tunnels' page in the OpenAI Platform."
    echo "3. Select 'Create tunnel' and create a new tunnel."
    echo "4. Copy the tunnel ID (tunnel_...) shown afterwards."
    echo "5. Under API Keys create a new secret key:"
    echo "   Owned by: You, Permissions: Restricted, only Tunnels: All selected."
    echo "6. Keep the tunnel ID and runtime API key ready."
    echo
    echo "The tunnel ID and runtime API key are NOT generated by this installer."
    echo "Without both values, section 4 cannot be completed."
    echo
    echo "Detailed preparation: README.md / installation guide"
    echo
    ;;
  *)
    echo "Ungültige Auswahl / Invalid selection." >&2
    exit 1
    ;;
esac

# Docker/containerd in unprivilegierten LXC benötigt einen Proxmox-LXC-Fix.
# PVE 8: lxc-pve >= 6.0.0-2; PVE 9: lxc-pve >= 6.0.5-2.
if command -v pveversion >/dev/null 2>&1 && command -v dpkg-query >/dev/null 2>&1; then
  PVE_VERSION="$(pveversion 2>/dev/null | sed -n 's#^pve-manager/\([0-9][0-9.]*\)/.*#\1#p')"
  PVE_MAJOR="${PVE_VERSION%%.*}"
  LXC_VERSION="$(dpkg-query -W -f='${Version}' lxc-pve 2>/dev/null || true)"
  MIN_LXC=""
  case "$PVE_MAJOR" in
    8) MIN_LXC="6.0.0-2" ;;
    9) MIN_LXC="6.0.5-2" ;;
  esac

  if [[ -n "$MIN_LXC" && -n "$LXC_VERSION" ]] && ! dpkg --compare-versions "$LXC_VERSION" ge "$MIN_LXC"; then
    echo
    echo "============================================================"
    if [[ "$LANG_MODE" == "de" ]]; then
      echo " Proxmox-Vorabprüfung fehlgeschlagen"
      echo "============================================================"
      echo "Installiert: lxc-pve $LXC_VERSION"
      echo "Benötigt für PVE $PVE_MAJOR: mindestens lxc-pve $MIN_LXC"
      echo
      echo "Ältere Versionen können Docker in unprivilegierten LXC mit"
      echo "net.ipv4.ip_unprivileged_port_start / permission denied abbrechen lassen."
      echo
      echo "Bitte zuerst auf dem Proxmox-Host aktualisieren:"
      echo "  apt update"
      echo "  apt install --only-upgrade lxc-pve"
      echo
      echo "Danach den Installer erneut starten. Es wurde noch kein LXC erstellt."
    else
      echo " Proxmox preflight check failed"
      echo "============================================================"
      echo "Installed: lxc-pve $LXC_VERSION"
      echo "Required for PVE $PVE_MAJOR: at least lxc-pve $MIN_LXC"
      echo
      echo "Older versions can make Docker fail inside unprivileged LXC with"
      echo "net.ipv4.ip_unprivileged_port_start / permission denied."
      echo
      echo "Update the Proxmox host first:"
      echo "  apt update"
      echo "  apt install --only-upgrade lxc-pve"
      echo
      echo "Then run the installer again. No LXC has been created yet."
    fi
    exit 1
  fi
fi

exec bash <(curl -fsSL "$BASE_URL/$SCRIPT")